export const products = [
  {
    id: 33,
    name: "Compact Power Bank 20000mAh",
    price: 52.99,
    sku: "PBK-033-GG",
    barcode: "9849839001753",
    quantity: 180,
    status: "In Stock",
    category: "Electronics",
    weight: "0.6",
    height: "12",
    width: "6",
    length: "2.5",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Color", value: "White" },
    ],
  },
  {
    id: 34,
    name: "Over-Ear Studio Headphones",
    price: 129.99,
    sku: "AUD-034-HH",
    barcode: "9849839001754",
    quantity: 95,
    status: "Published",
    category: "Audio",
    weight: "0.9",
    height: "25",
    width: "20",
    length: "10",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Color", value: "Gray" },
    ],
  },
  {
    id: 35,
    name: "Leather Travel Wallet",
    price: 48.0,
    sku: "ACC-035-II",
    barcode: "9849839001755",
    quantity: 140,
    status: "In Stock",
    category: "Accessories",
    weight: "0.3",
    height: "12",
    width: "9",
    length: "2",
    variations: [
      { type: "Color", value: "Brown" },
      { type: "Color", value: "Tan" },
    ],
  },
  {
    id: 36,
    name: "Anti-Theft Laptop Backpack",
    price: 89.95,
    sku: "BAG-036-JJ",
    barcode: "9849839001756",
    quantity: 70,
    status: "Published",
    category: "Bags",
    weight: "1.1",
    height: "45",
    width: "30",
    length: "18",
    variations: [
      { type: "Color", value: "Gray" },
      { type: "Color", value: "Navy" },
    ],
  },
  {
    id: 37,
    name: "Stainless Steel Thermos",
    price: 26.99,
    sku: "DRK-037-KK",
    barcode: "9849839001757",
    quantity: 200,
    status: "In Stock",
    category: "Drinkware",
    weight: "0.5",
    height: "28",
    width: "7",
    length: "7",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Color", value: "Red" },
    ],
  },
  {
    id: 38,
    name: "Foldable LED Desk Light",
    price: 44.5,
    sku: "LGT-038-LL",
    barcode: "9849839001758",
    quantity: 85,
    status: "Published",
    category: "Lighting",
    weight: "0.9",
    height: "35",
    width: "15",
    length: "8",
    variations: [
      { type: "Color", value: "White" },
      { type: "Color", value: "Black" },
    ],
  },
  {
    id: 39,
    name: "Adjustable Resistance Bands Set",
    price: 36.25,
    sku: "FIT-039-MM",
    barcode: "9849839001759",
    quantity: 150,
    status: "In Stock",
    category: "Fitness",
    weight: "0.7",
    height: "10",
    width: "25",
    length: "15",
    variations: [
      { type: "Color", value: "Multi" },
      { type: "Color", value: "Black" },
    ],
  },
  {
    id: 40,
    name: "Slimline Laptop Case 15”",
    price: 39.0,
    sku: "LAP-040-NN",
    barcode: "9849839001760",
    quantity: 120,
    status: "Published",
    category: "Laptop Accessories",
    weight: "0.4",
    height: "28",
    width: "38",
    length: "3",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Color", value: "Charcoal" },
    ],
  },
  {
    id: 41,
    name: "RGB Gaming Keyboard",
    price: 69.95,
    sku: "GAM-041-OO",
    barcode: "9849839001761",
    quantity: 110,
    status: "In Stock",
    category: "Gaming",
    weight: "0.8",
    height: "5",
    width: "15",
    length: "45",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Lighting", value: "RGB" },
    ],
  },
  {
    id: 42,
    name: "Smart Motion Sensor Plug",
    price: 34.0,
    sku: "HOM-042-PP",
    barcode: "9849839001762",
    quantity: 170,
    status: "Published",
    category: "Home Automation",
    weight: "0.25",
    height: "6",
    width: "5",
    length: "6",
    variations: [
      { type: "Color", value: "White" },
      { type: "Feature", value: "Motion Sensor" },
    ],
  },
  {
    id: 43,
    name: "USB-C Fast Charging Cable",
    price: 11.5,
    sku: "ELC-043-QQ",
    barcode: "9849839001763",
    quantity: 300,
    status: "In Stock",
    category: "Electronics",
    weight: "0.1",
    height: "2",
    width: "8",
    length: "15",
    variations: [
      { type: "Color", value: "White" },
      { type: "Length", value: "1.5m" },
    ],
  },
  {
    id: 44,
    name: "Bluetooth Soundbar Speaker",
    price: 74.99,
    sku: "AUD-044-RR",
    barcode: "9849839001764",
    quantity: 65,
    status: "Published",
    category: "Audio",
    weight: "1.4",
    height: "8",
    width: "10",
    length: "45",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Power", value: "20W" },
    ],
  },
  {
    id: 45,
    name: "Unisex Sports Sunglasses",
    price: 29.99,
    sku: "ACC-045-SS",
    barcode: "9849839001765",
    quantity: 250,
    status: "In Stock",
    category: "Accessories",
    weight: "0.08",
    height: "5",
    width: "14",
    length: "14",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Lens", value: "Polarized" },
    ],
  },
  {
    id: 46,
    name: "Waterproof Hiking Backpack",
    price: 105.0,
    sku: "BAG-046-TT",
    barcode: "9849839001766",
    quantity: 45,
    status: "Published",
    category: "Bags",
    weight: "1.3",
    height: "55",
    width: "32",
    length: "20",
    variations: [
      { type: "Color", value: "Green" },
      { type: "Capacity", value: "40L" },
    ],
  },
  {
    id: 47,
    name: "Insulated Travel Mug",
    price: 22.95,
    sku: "DRK-047-UU",
    barcode: "9849839001767",
    quantity: 180,
    status: "In Stock",
    category: "Drinkware",
    weight: "0.35",
    height: "20",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Matte Black" },
      { type: "Size", value: "450ml" },
    ],
  },
  {
    id: 48,
    name: "Clip-On Reading Light",
    price: 16.75,
    sku: "LGT-048-VV",
    barcode: "9849839001768",
    quantity: 190,
    status: "Published",
    category: "Lighting",
    weight: "0.2",
    height: "6",
    width: "4",
    length: "10",
    variations: [
      { type: "Color", value: "White" },
      { type: "Light", value: "Warm" },
    ],
  },
  {
    id: 49,
    name: "Adjustable Yoga Mat Strap",
    price: 14.0,
    sku: "FIT-049-WW",
    barcode: "9849839001769",
    quantity: 210,
    status: "In Stock",
    category: "Fitness",
    weight: "0.12",
    height: "3",
    width: "4",
    length: "120",
    variations: [
      { type: "Color", value: "Purple" },
      { type: "Material", value: "Cotton" },
    ],
  },
  {
    id: 50,
    name: "Cooling Laptop Stand",
    price: 59.95,
    sku: "LAP-050-XX",
    barcode: "9849839001770",
    quantity: 100,
    status: "Published",
    category: "Laptop Accessories",
    weight: "0.9",
    height: "8",
    width: "30",
    length: "26",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Fans", value: "Dual" },
    ],
  },
  {
    id: 51,
    name: "Gaming Controller Charging Dock",
    price: 33.99,
    sku: "GAM-051-YY",
    barcode: "9849839001771",
    quantity: 130,
    status: "In Stock",
    category: "Gaming",
    weight: "0.45",
    height: "6",
    width: "12",
    length: "20",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Port", value: "Dual USB" },
    ],
  },
  {
    id: 52,
    name: "Smart LED Bulb - Wi-Fi Enabled",
    price: 18.49,
    sku: "HOM-052-ZZ",
    barcode: "9849839001772",
    quantity: 275,
    status: "Published",
    category: "Home Automation",
    weight: "0.18",
    height: "12",
    width: "6",
    length: "6",
    variations: [
      { type: "Color", value: "RGB" },
      { type: "Base", value: "E27" },
    ],
  },
  {
    id: 53,
    name: "Portable Solar Charger",
    price: 49.99,
    sku: "ELC-053-AA",
    barcode: "9849839001773",
    quantity: 95,
    status: "In Stock",
    category: "Electronics",
    weight: "0.7",
    height: "10",
    width: "15",
    length: "2",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Capacity", value: "20000mAh" },
    ],
  },
  {
    id: 54,
    name: "Portable Bluetooth Speaker",
    price: 59.99,
    sku: "AUD-054-BB",
    barcode: "9849839001774",
    quantity: 150,
    status: "Published",
    category: "Audio",
    weight: "0.9",
    height: "8",
    width: "8",
    length: "20",
    variations: [
      { type: "Color", value: "Blue" },
      { type: "Color", value: "Black" },
    ],
  },
  {
    id: 55,
    name: "Adjustable Wallet Card Holder",
    price: 14.5,
    sku: "ACC-055-CC",
    barcode: "9849839001775",
    quantity: 220,
    status: "In Stock",
    category: "Accessories",
    weight: "0.1",
    height: "7",
    width: "10",
    length: "1",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Color", value: "Brown" },
    ],
  },
  {
    id: 56,
    name: "Urban Travel Backpack",
    price: 85.0,
    sku: "BAG-056-DD",
    barcode: "9849839001776",
    quantity: 80,
    status: "Published",
    category: "Bags",
    weight: "1.2",
    height: "45",
    width: "30",
    length: "18",
    variations: [
      { type: "Color", value: "Navy" },
      { type: "Capacity", value: "35L" },
    ],
  },
  {
    id: 57,
    name: "Thermal Insulated Bottle",
    price: 29.0,
    sku: "DRK-057-EE",
    barcode: "9849839001777",
    quantity: 180,
    status: "In Stock",
    category: "Drinkware",
    weight: "0.45",
    height: "26",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Color", value: "Black" },
    ],
  },
  {
    id: 58,
    name: "Touch-Sensitive Desk Lamp",
    price: 39.99,
    sku: "LGT-058-FF",
    barcode: "9849839001778",
    quantity: 125,
    status: "Published",
    category: "Lighting",
    weight: "1.0",
    height: "40",
    width: "15",
    length: "15",
    variations: [
      { type: "Color", value: "White" },
      { type: "Color", value: "Black" },
    ],
  },
  {
    id: 59,
    name: "Kettlebell Weights Set",
    price: 120.0,
    sku: "FIT-059-GG",
    barcode: "9849839001779",
    quantity: 60,
    status: "In Stock",
    category: "Fitness",
    weight: "10.5",
    height: "25",
    width: "25",
    length: "25",
    variations: [
      { type: "Weight", value: "10kg" },
      { type: "Weight", value: "16kg" },
    ],
  },
  {
    id: 60,
    name: "Adjustable Ergonomic Laptop Stand",
    price: 49.99,
    sku: "LAP-060-HH",
    barcode: "9849839001780",
    quantity: 110,
    status: "Published",
    category: "Laptop Accessories",
    weight: "0.6",
    height: "7",
    width: "27",
    length: "25",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Material", value: "Aluminum" },
    ],
  },
  {
    id: 61,
    name: "Ergonomic Gaming Mouse",
    price: 29.95,
    sku: "GAM-061-II",
    barcode: "9849839001781",
    quantity: 130,
    status: "In Stock",
    category: "Gaming",
    weight: "0.2",
    height: "4",
    width: "6",
    length: "12",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Color", value: "Red" },
    ],
  },
  {
    id: 62,
    name: "Smart Home Thermostat",
    price: 149.99,
    sku: "HOM-062-JJ",
    barcode: "9849839001782",
    quantity: 90,
    status: "Published",
    category: "Home Automation",
    weight: "0.45",
    height: "10",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "White" },
      { type: "Connectivity", value: "Wi-Fi" },
    ],
  },
  {
    id: 63,
    name: "Bluetooth Wireless Earbuds",
    price: 45.0,
    sku: "ELC-063-KK",
    barcode: "9849839001783",
    quantity: 250,
    status: "In Stock",
    category: "Electronics",
    weight: "0.1",
    height: "3",
    width: "5",
    length: "5",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Battery", value: "Up to 10 hours" },
    ],
  },
  {
    id: 64,
    name: "Noise Cancelling Headphones",
    price: 199.99,
    sku: "AUD-064-LL",
    barcode: "9849839001784",
    quantity: 50,
    status: "Published",
    category: "Audio",
    weight: "0.8",
    height: "22",
    width: "18",
    length: "8",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Noise Cancelling" },
    ],
  },
  {
    id: 65,
    name: "Leather Card Wallet",
    price: 22.0,
    sku: "ACC-065-MM",
    barcode: "9849839001785",
    quantity: 150,
    status: "In Stock",
    category: "Accessories",
    weight: "0.1",
    height: "6",
    width: "10",
    length: "1.5",
    variations: [
      { type: "Color", value: "Brown" },
      { type: "Color", value: "Black" },
    ],
  },
  {
    id: 66,
    name: "Expandable Duffel Bag",
    price: 75.0,
    sku: "BAG-066-NN",
    barcode: "9849839001786",
    quantity: 120,
    status: "Published",
    category: "Bags",
    weight: "1.5",
    height: "40",
    width: "30",
    length: "15",
    variations: [
      { type: "Color", value: "Gray" },
      { type: "Capacity", value: "40L" },
    ],
  },
  {
    id: 67,
    name: "Insulated Water Bottle",
    price: 19.95,
    sku: "DRK-067-OO",
    barcode: "9849839001787",
    quantity: 200,
    status: "In Stock",
    category: "Drinkware",
    weight: "0.35",
    height: "22",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Material", value: "Stainless Steel" },
    ],
  },
  {
    id: 68,
    name: "Smart LED Floor Lamp",
    price: 89.99,
    sku: "LGT-068-PP",
    barcode: "9849839001788",
    quantity: 75,
    status: "In Stock",
    category: "Lighting",
    weight: "1.2",
    height: "100",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "White" },
      { type: "Feature", value: "Smart Control" },
    ],
  },
  {
    id: 69,
    name: "Resistance Bands for Strength Training",
    price: 19.99,
    sku: "FIT-069-QQ",
    barcode: "9849839001789",
    quantity: 250,
    status: "In Stock",
    category: "Fitness",
    weight: "0.3",
    height: "5",
    width: "15",
    length: "15",
    variations: [
      { type: "Color", value: "Blue" },
      { type: "Resistance", value: "Light/Medium/Heavy" },
    ],
  },
  {
    id: 70,
    name: "Adjustable Laptop Cooling Pad",
    price: 39.95,
    sku: "LAP-070-RR",
    barcode: "9849839001790",
    quantity: 110,
    status: "Published",
    category: "Laptop Accessories",
    weight: "0.8",
    height: "3",
    width: "30",
    length: "30",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Dual Fan" },
    ],
  },
  {
    id: 71,
    name: "RGB Gaming Mouse Pad",
    price: 24.99,
    sku: "GAM-071-SS",
    barcode: "9849839001791",
    quantity: 150,
    status: "In Stock",
    category: "Gaming",
    weight: "0.3",
    height: "5",
    width: "30",
    length: "25",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Lighting", value: "RGB" },
    ],
  },
  {
    id: 72,
    name: "Smart Light Switch",
    price: 39.99,
    sku: "HOM-072-TT",
    barcode: "9849839001792",
    quantity: 180,
    status: "In Stock",
    category: "Home Automation",
    weight: "0.3",
    height: "8",
    width: "5",
    length: "5",
    variations: [
      { type: "Color", value: "White" },
      { type: "Connectivity", value: "Wi-Fi" },
    ],
  },
  {
    id: 73,
    name: "Multi-Tool Pocket Knife",
    price: 22.5,
    sku: "ACC-073-UU",
    barcode: "9849839001793",
    quantity: 180,
    status: "Published",
    category: "Accessories",
    weight: "0.3",
    height: "3",
    width: "10",
    length: "15",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Material", value: "Stainless Steel" },
    ],
  },
  {
    id: 74,
    name: "Outdoor Camping Hammock",
    price: 35.99,
    sku: "OUT-074-VV",
    barcode: "9849839001794",
    quantity: 100,
    status: "In Stock",
    category: "Outdoor",
    weight: "0.9",
    height: "10",
    width: "10",
    length: "20",
    variations: [
      { type: "Color", value: "Green" },
      { type: "Material", value: "Nylon" },
    ],
  },
  {
    id: 75,
    name: "Eco-Friendly Reusable Coffee Cup",
    price: 16.0,
    sku: "DRK-075-WW",
    barcode: "9849839001795",
    quantity: 150,
    status: "Published",
    category: "Drinkware",
    weight: "0.25",
    height: "12",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Beige" },
      { type: "Material", value: "Bamboo" },
    ],
  },
  {
    id: 76,
    name: "Solar-Powered Garden Lights",
    price: 18.99,
    sku: "LGT-076-XX",
    barcode: "9849839001796",
    quantity: 200,
    status: "In Stock",
    category: "Lighting",
    weight: "0.5",
    height: "20",
    width: "6",
    length: "6",
    variations: [
      { type: "Color", value: "Warm White" },
      { type: "Feature", value: "Solar" },
    ],
  },
  {
    id: 77,
    name: "Waterproof Bluetooth Speaker",
    price: 39.99,
    sku: "AUD-077-YY",
    barcode: "9849839001797",
    quantity: 180,
    status: "In Stock",
    category: "Audio",
    weight: "0.7",
    height: "7",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Blue" },
      { type: "Waterproof", value: "IPX7" },
    ],
  },
  {
    id: 78,
    name: "Electric Massager for Neck & Shoulders",
    price: 59.0,
    sku: "HEA-078-ZZ",
    barcode: "9849839001798",
    quantity: 50,
    status: "Published",
    category: "Health & Wellness",
    weight: "0.8",
    height: "12",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Heating Function" },
    ],
  },
  {
    id: 79,
    name: "Bamboo Bath Towel Set",
    price: 49.95,
    sku: "HOM-079-AAA",
    barcode: "9849839001799",
    quantity: 200,
    status: "In Stock",
    category: "Home",
    weight: "1.5",
    height: "35",
    width: "25",
    length: "25",
    variations: [
      { type: "Color", value: "Gray" },
      { type: "Material", value: "Bamboo" },
    ],
  },
  {
    id: 80,
    name: "Resistance Bands Set for Yoga",
    price: 24.99,
    sku: "FIT-080-BBB",
    barcode: "9849839001800",
    quantity: 250,
    status: "In Stock",
    category: "Fitness",
    weight: "0.6",
    height: "3",
    width: "15",
    length: "20",
    variations: [
      { type: "Resistance", value: "Light/Medium/Heavy" },
      { type: "Material", value: "Latex" },
    ],
  },
  {
    id: 81,
    name: "Cordless Hair Clippers",
    price: 39.99,
    sku: "HEA-081-CCC",
    barcode: "9849839001801",
    quantity: 130,
    status: "In Stock",
    category: "Health & Wellness",
    weight: "0.5",
    height: "16",
    width: "4",
    length: "4",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Cordless" },
    ],
  },
  {
    id: 82,
    name: "Smart Plugs - Wi-Fi Enabled",
    price: 22.99,
    sku: "HOM-082-DDD",
    barcode: "9849839001802",
    quantity: 220,
    status: "Published",
    category: "Home Automation",
    weight: "0.1",
    height: "8",
    width: "5",
    length: "5",
    variations: [
      { type: "Color", value: "White" },
      { type: "Connectivity", value: "Wi-Fi" },
    ],
  },
  {
    id: 83,
    name: "Smartphone Car Mount Holder",
    price: 15.99,
    sku: "ACC-083-EEE",
    barcode: "9849839001803",
    quantity: 180,
    status: "In Stock",
    category: "Accessories",
    weight: "0.2",
    height: "5",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "360 Rotation" },
    ],
  },
  {
    id: 84,
    name: "Camping Tent for 2 People",
    price: 79.99,
    sku: "OUT-084-FFF",
    barcode: "9849839001804",
    quantity: 70,
    status: "In Stock",
    category: "Outdoor",
    weight: "2.0",
    height: "130",
    width: "200",
    length: "200",
    variations: [
      { type: "Color", value: "Green" },
      { type: "Size", value: "2 Person" },
    ],
  },
  {
    id: 85,
    name: "Stainless Steel Insulated Travel Mug",
    price: 18.99,
    sku: "DRK-085-GGG",
    barcode: "9849839001805",
    quantity: 150,
    status: "In Stock",
    category: "Drinkware",
    weight: "0.45",
    height: "22",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Material", value: "Stainless Steel" },
    ],
  },
  {
    id: 86,
    name: "Outdoor Solar Garden Path Lights",
    price: 24.99,
    sku: "LGT-086-HHH",
    barcode: "9849839001806",
    quantity: 200,
    status: "In Stock",
    category: "Lighting",
    weight: "0.3",
    height: "18",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Warm White" },
      { type: "Feature", value: "Solar Powered" },
    ],
  },
  {
    id: 87,
    name: "Wireless Smart Earbuds with Charging Case",
    price: 49.99,
    sku: "AUD-087-III",
    barcode: "9849839001807",
    quantity: 180,
    status: "Published",
    category: "Audio",
    weight: "0.2",
    height: "3",
    width: "5",
    length: "5",
    variations: [
      { type: "Color", value: "White" },
      { type: "Battery", value: "Up to 12 hours" },
    ],
  },
  {
    id: 88,
    name: "Portable BBQ Grill Set",
    price: 69.99,
    sku: "OUT-088-JJJ",
    barcode: "9849839001808",
    quantity: 150,
    status: "In Stock",
    category: "Outdoor",
    weight: "3.5",
    height: "35",
    width: "35",
    length: "10",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Portable" },
    ],
  },
  {
    id: 89,
    name: "Compact Air Purifier for Home",
    price: 99.99,
    sku: "HOM-089-KKK",
    barcode: "9849839001809",
    quantity: 120,
    status: "In Stock",
    category: "Home",
    weight: "2.0",
    height: "40",
    width: "25",
    length: "25",
    variations: [
      { type: "Color", value: "White" },
      { type: "Feature", value: "HEPA Filter" },
    ],
  },
  {
    id: 90,
    name: "Portable Fitness Jump Rope",
    price: 14.99,
    sku: "FIT-090-LLL",
    barcode: "9849839001810",
    quantity: 250,
    status: "In Stock",
    category: "Fitness",
    weight: "0.3",
    height: "1",
    width: "25",
    length: "25",
    variations: [
      { type: "Color", value: "Red" },
      { type: "Material", value: "PVC" },
    ],
  },
  {
    id: 91,
    name: "Foldable Yoga Mat",
    price: 29.99,
    sku: "FIT-091-MMM",
    barcode: "9849839001811",
    quantity: 200,
    status: "In Stock",
    category: "Fitness",
    weight: "1.0",
    height: "5",
    width: "60",
    length: "180",
    variations: [
      { type: "Color", value: "Purple" },
      { type: "Material", value: "TPE" },
    ],
  },
  {
    id: 92,
    name: "Wi-Fi Enabled Smart Door Lock",
    price: 129.99,
    sku: "HOM-092-NNN",
    barcode: "9849839001812",
    quantity: 80,
    status: "Published",
    category: "Home Automation",
    weight: "1.5",
    height: "15",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Connectivity", value: "Wi-Fi" },
    ],
  },
  {
    id: 93,
    name: "Ultra Lightweight Backpack",
    price: 39.99,
    sku: "BAG-093-OOO",
    barcode: "9849839001813",
    quantity: 150,
    status: "In Stock",
    category: "Bags",
    weight: "0.4",
    height: "45",
    width: "30",
    length: "15",
    variations: [
      { type: "Color", value: "Gray" },
      { type: "Feature", value: "Water-Resistant" },
    ],
  },
  {
    id: 94,
    name: "Electric Toothbrush with Smart Timer",
    price: 29.99,
    sku: "HEA-094-PPP",
    barcode: "9849839001814",
    quantity: 100,
    status: "Published",
    category: "Health & Wellness",
    weight: "0.3",
    height: "25",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "White" },
      { type: "Feature", value: "Smart Timer" },
    ],
  },
  {
    id: 95,
    name: "Digital Smart Scale",
    price: 49.99,
    sku: "HEA-095-QQQ",
    barcode: "9849839001815",
    quantity: 200,
    status: "In Stock",
    category: "Health & Wellness",
    weight: "1.2",
    height: "30",
    width: "30",
    length: "5",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Bluetooth" },
    ],
  },
  {
    id: 96,
    name: "Foldable Pet Travel Carrier",
    price: 39.99,
    sku: "PET-096-RRR",
    barcode: "9849839001816",
    quantity: 120,
    status: "Published",
    category: "Pets",
    weight: "1.0",
    height: "40",
    width: "30",
    length: "30",
    variations: [
      { type: "Color", value: "Gray" },
      { type: "Size", value: "Medium" },
    ],
  },
  {
    id: 97,
    name: "Shoe Rack Organizer",
    price: 19.99,
    sku: "HOM-097-SSS",
    barcode: "9849839001817",
    quantity: 250,
    status: "In Stock",
    category: "Home",
    weight: "1.5",
    height: "25",
    width: "70",
    length: "20",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Material", value: "Metal" },
    ],
  },
  {
    id: 98,
    name: "Compact Portable Heater",
    price: 59.99,
    sku: "HOM-098-TTT",
    barcode: "9849839001818",
    quantity: 180,
    status: "In Stock",
    category: "Home",
    weight: "1.0",
    height: "25",
    width: "20",
    length: "20",
    variations: [
      { type: "Color", value: "White" },
      { type: "Feature", value: "Portable" },
    ],
  },
  {
    id: 99,
    name: "Reversible Comforter Set",
    price: 69.99,
    sku: "HOM-099-UUU",
    barcode: "9849839001819",
    quantity: 200,
    status: "In Stock",
    category: "Home",
    weight: "2.0",
    height: "15",
    width: "50",
    length: "70",
    variations: [
      { type: "Color", value: "Navy Blue" },
      { type: "Material", value: "Cotton" },
    ],
  },
  {
    id: 100,
    name: "Self-Watering Planter",
    price: 29.99,
    sku: "GAR-100-VVV",
    barcode: "9849839001820",
    quantity: 180,
    status: "In Stock",
    category: "Gardening",
    weight: "1.2",
    height: "15",
    width: "15",
    length: "15",
    variations: [
      { type: "Color", value: "Green" },
      { type: "Feature", value: "Self-Watering" },
    ],
  },
  {
    id: 101,
    name: "Collapsible Camping Stool",
    price: 22.0,
    sku: "OUT-101-WWW",
    barcode: "9849839001821",
    quantity: 150,
    status: "In Stock",
    category: "Outdoor",
    weight: "0.8",
    height: "35",
    width: "30",
    length: "30",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Foldable" },
    ],
  },
  {
    id: 102,
    name: "Fitness Tracker Watch",
    price: 49.99,
    sku: "FIT-102-XXX",
    barcode: "9849839001822",
    quantity: 200,
    status: "Published",
    category: "Fitness",
    weight: "0.5",
    height: "10",
    width: "5",
    length: "5",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Heart Rate Monitor" },
    ],
  },
  {
    id: 103,
    name: "Mini Bluetooth Speaker",
    price: 25.99,
    sku: "AUD-103-YYY",
    barcode: "9849839001823",
    quantity: 250,
    status: "Published",
    category: "Audio",
    weight: "0.3",
    height: "6",
    width: "6",
    length: "6",
    variations: [
      { type: "Color", value: "Red" },
      { type: "Battery Life", value: "8 Hours" },
    ],
  },
  {
    id: 104,
    name: "Stainless Steel Travel Tumbler",
    price: 19.99,
    sku: "DRK-104-ZZZ",
    barcode: "9849839001824",
    quantity: 300,
    status: "In Stock",
    category: "Drinkware",
    weight: "0.4",
    height: "24",
    width: "8",
    length: "8",
    variations: [
      { type: "Color", value: "Blue" },
      { type: "Material", value: "Stainless Steel" },
    ],
  },
  {
    id: 105,
    name: "Smart Wi-Fi Thermostat",
    price: 129.99,
    sku: "HOM-105-AAA",
    barcode: "9849839001825",
    quantity: 100,
    status: "In Stock",
    category: "Home Automation",
    weight: "1.0",
    height: "10",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "White" },
      { type: "Feature", value: "Wi-Fi Enabled" },
    ],
  },
  {
    id: 106,
    name: "Compact Air Compressor",
    price: 49.99,
    sku: "AUT-106-BBB",
    barcode: "9849839001826",
    quantity: 150,
    status: "In Stock",
    category: "Automotive",
    weight: "1.5",
    height: "20",
    width: "15",
    length: "15",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Feature", value: "Portable" },
    ],
  },
  {
    id: 107,
    name: "Car Vacuum Cleaner",
    price: 39.99,
    sku: "AUT-107-CCC",
    barcode: "9849839001827",
    quantity: 180,
    status: "In Stock",
    category: "Automotive",
    weight: "1.2",
    height: "15",
    width: "10",
    length: "10",
    variations: [
      { type: "Color", value: "Red" },
      { type: "Feature", value: "Cordless" },
    ],
  },
  {
    id: 108,
    name: "Wall Mounted LED Mirror",
    price: 89.99,
    sku: "HOM-108-DDD",
    barcode: "9849839001828",
    quantity: 70,
    status: "In Stock",
    category: "Home",
    weight: "3.0",
    height: "50",
    width: "40",
    length: "5",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Feature", value: "LED Lighting" },
    ],
  },
  {
    id: 109,
    name: "Adjustable Laptop Stand",
    price: 29.99,
    sku: "ACC-109-EEE",
    barcode: "9849839001829",
    quantity: 200,
    status: "Published",
    category: "Accessories",
    weight: "0.6",
    height: "25",
    width: "30",
    length: "30",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Material", value: "Aluminum" },
    ],
  },
  {
    id: 110,
    name: "Portable Power Bank - 10000mAh",
    price: 29.99,
    sku: "ACC-110-FFF",
    barcode: "9849839001830",
    quantity: 250,
    status: "In Stock",
    category: "Accessories",
    weight: "0.3",
    height: "3",
    width: "7",
    length: "14",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Capacity", value: "10000mAh" },
    ],
  },
  {
    id: 111,
    name: "Bluetooth Headphones",
    price: 59.99,
    sku: "AUD-111-GGG",
    barcode: "9849839001831",
    quantity: 180,
    status: "In Stock",
    category: "Audio",
    weight: "0.4",
    height: "18",
    width: "18",
    length: "8",
    variations: [
      { type: "Color", value: "Black" },
      { type: "Battery Life", value: "20 Hours" },
    ],
    added: "24 Dec 2022",
  },
  {
    id: 112,
    name: "Kitchen Knife Set - 5 Pieces",
    price: 49.99,
    sku: "KIT-112-HHH",
    barcode: "9849839001832",
    quantity: 100,
    status: "In Stock",
    category: "Kitchen",
    weight: "2.0",
    height: "25",
    width: "20",
    length: "5",
    variations: [
      { type: "Color", value: "Silver" },
      { type: "Material", value: "Stainless Steel" },
    ],
    added: "24 Dec 2022",
  },
];
